from scripting.action import Action
import random
from scripting.dice_roll_action import DiceRollAction
"Working on a way to create a dictionary of lists. I am not certain how to return what they have gotten "
class RollTable(Action):
    def __init__(self):
        self.tavern = {1: "A group of bandits attack the tavern", 2: "The bartender offers free drinks in exchange for killing some rodents running around the place", 3: "The barkeep has information related to the parties quest, or a particular player's story", 4: "A pair of grizzled veterens are harrasing the barmaids", 5: "A noble staying there has bought out all the rooms, and stable stalls at the tavern despite him only having two bodyguards with him. He seems to have a strong dislike of the party", 6: "An traveling magician performing at the tavern, has a spell go terribly awry. Roll on the Wild magic table."}
        self.weather = {1: "The weather for the day is bright and sunny, with no clouds in the sky." , 2: "The weather for the day is fairly clear, with a few stray clouds in the sky.", 3: "The weather is mostly cloudy, with some sunlight.", 4: "The weather is wet and dreary, with a slow drizzle and mist for most of the day (vision reduced to 1000 meters)", 5 :"A terrible lightning storm rolls in, with heavy rain, lightning, and strong winds (if you want to be cruel you can add a tornado the players must escape from)", 6: "To the parties horror, during the night a cold front appeared, dropping the area below freezing, and causing a blizzard in the area (if in a warm area this can be unnaturally caused)"}
        self.boat_travel = {1:"Nothing of note occurs" , 2: "The day is partly cloudy, but nothing of note occurs ", 3: "The party can see a ship off in the distance on fire. (This would be a merchant ship that was attacked)", 4: "The party sees a ship with a skull and crossbones on its flag barreling towards them", 5 :"A storm hits them while at sea, causing the waves to grow larger, and the party must try to keep from being swept overboard", 6: "Changes based on party level 1-8(The party hears a beautiful voice singing, they have a strange urge to go towards it. DC 15 wisdom check or be charmed by the siren luring them to a small island) 9-20 (The party seas the siluette of a snake in the water as a young sea serpent bursts out of the water.)"}
        self.horse_travel = {1: "Nothing of note occurs" , 2: "You come upon a camp with the charred corpses of the fallen, an investigation of the camp would find some rations that are still good, and a few silver and gold pieces.", 3: "One of the horses falls ill to an unknown ailment", 4: "In the night the party is surrounded by 1d4 bandits", 5 :"The party passes by a cavern with a glint of metal inside it. Upon investigating the party would the cave filled with scimitars, as well as 2 rust monsters feeding upon them. Roll 1d10, with a 1-9 the party can find a scimitar +1, and with a 10 the party finds a scimitar of polymorph", 6: "Roll a d20, on a 1-19 nothing occurs, on a 20 a freaking ancient Red dragon bursts out of a mountainside, heading in the direction of the party (although it does not currently see them)."}
        self.severe_weather = {1: "The ground begins to quake, the party must make dexterity saving throws to avoid falling down." , 2: "A tornado touches down in the distance", 3: "The party is in the midst of an extreme lightning storm, they must roll dexterity checks to avoid getting hit by lightning", 4: "A blizzard rolls in, with heavy snowfall the parties vision is reduced to 100 meters and will begin to take cold damage without protection.", 5 :"Extreme rainfall from the mountains has begun to send tides of water towards the party", 6: "A nearby mountain errupts with ash and fire, the party must avoid pyroclastic debris and escape the area."}
        self.monster_attack = {1: "The party spots a group of 5 goblins" , 2: "The party walks past a pair of mounds, and feel a cold chill as two specters appear.", 3: "The party sees a rampaging ogre in the distance", 4: "The party hears chanting coming from nearby, an investigation would find 5 cultists in a pentagram formation around a young boy.", 5 :"A hippogriff dives at the party from above", 6: "The party sees 4 zombies burst out of the ground near them"}
        self.current_roll_tables= {"tavern" : self.tavern ,"weather" : self.weather,"boat travel" : self.boat_travel,"horse travel": self.horse_travel,"severe weather": self.severe_weather,"monster attack": self.monster_attack}
    # print(f"{current_roll_tables}")
    # user_input = input("What kind of roll table do you want 1-10")
    # selected_table = current_roll_tables[user_input]

    def execute(self, user_input):
        dice_roll = DiceRollAction.execute(self.current_roll_tables[user_input].size() )
#Might need to indicate a +1 for safety reasons
        self.current_roll_tables[user_input[dice_roll[2]]]
        return super().execute()
